### PR TITLE
Fix: :unicode_util.cp/1 JS port diverges from Erlang behaviour

### LINKED ISSUE #636: Bug: :unicode_util.cp/1 port diverges from Erlang behaviour
When passing a list with multiple elements where at least one element is invalid, Erlang raises:
no function clause matching in :unicode_util.cpl/2

The JS port instead raises:
no function clause matching in :unicode_util.cp/1

Erlang example:
`iex(3)> :unicode_util.cp [:a, :b]
** (FunctionClauseError) no function clause matching in :unicode_util.cpl/2

    The following arguments were given to :unicode_util.cpl/2:

        # 1
        :a

        # 2
        [:b]

    (stdlib 6.2) unicode_util.erl:322: :unicode_util.cpl/2
    iex:3: (file)`

JS example:
`> Erlang_UnicodeUtil["cp/1"](Type.list([Type.atom("a"), Type.atom("b")]))
Uncaught:
HologramBoxedError: (FunctionClauseError) no function clause matching in :unicode_util.cp/1

The following arguments were given to :unicode_util.cp/1:

    # 1
    :a

    at error/2 (file:///home/petarj/dev/hologram/assets/js/erlang/erlang.mjs:718:11)
    at error/1 (file:///home/petarj/dev/hologram/assets/js/erlang/erlang.mjs:709:22)
    at Interpreter.raiseError (file:///home/petarj/dev/hologram/assets/js/interpreter.mjs:818:22)
    at Interpreter.raiseFunctionClauseError (file:///home/petarj/dev/hologram/assets/js/interpreter.mjs:822:17)
    at processListElement (file:///home/petarj/dev/hologram/assets/js/erlang/unicode_util.mjs:156:21)
    at cp/1 (file:///home/petarj/dev/hologram/assets/js/erlang/unicode_util.mjs:165:30) {
  struct: {
    type: 'map',
    data: {
      'atom(__exception__)': [Array],
      'atom(message)': [Array],
      'atom(__struct__)': [Array]
    }
  }
}`

### PR DESCRIPTION
**Pull request by mward-sudo**
Closes #636 

It may be better to use internal const function helpers rather than private erlang functions, but this approach closely mimics the erlang implementation.

## Summary by CodeRabbit

* **Tests**
  * Added extensive Elixir and JavaScript test suites for Unicode codepoint handling, covering improper lists, mixed content, deep nesting, and many UTF‑8 edge cases (valid, invalid, truncated, overlong, etc.).

* **Refactor**
  * Reorganized Unicode processing into a continuation-driven, layered approach to unify list/binary handling, improve UTF‑8 validation and error reporting, and better preserve proper/improper tail semantics.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: test/javascript/erlang/unicode_util_test.mjs [hunk 1]
```diff
@@ -373,5 +386,427 @@ describe("Erlang_UnicodeUtil", () => {
...
+
+    describe("UTF-8 and encoding edge cases", () => {
+      it("handles codepoint at 0 (null character)", () => {
+        const input = Type.list([Type.integer(0)]);
+        const result = cp(input);
+
+        assert.deepStrictEqual(result, Type.list([Type.integer(0)]));
+      });
+
+      it("handles binary containing null character", () => {
```
Comment (bartblast) [inline test/javascript/erlang/unicode_util_test.mjs:715]: This test doesn't match the Elixir consistency test.

The Elixir test uses a binary input:
```elixir
assert :unicode_util.cp(<<0, 97, 98>>) == [0 | <<97, 98>>]
```

But this JS test uses a list with an integer and binary:
```javascript
const input = Type.list([Type.integer(0), Type.bitstring("ab")]);
```

These test different code paths. The JS test should use:
```javascript
const input = Bitstring.fromBytes([0, 97, 98]);
const result = cp(input);

assert.deepStrictEqual(
  result,
  Type.improperList([Type.integer(0), Bitstring.fromBytes([97, 98])]),
);
```

File: test/javascript/erlang/unicode_util_test.mjs [hunk 2]
```diff
@@ -373,5 +386,427 @@ describe("Erlang_UnicodeUtil", () => {
...
+      });
+
+      it("handles first codepoint above BMP", () => {
+        const input = Type.list([Type.integer(0x10000)]);
+        const result = cp(input);
+
+        assert.deepStrictEqual(result, Type.list([Type.integer(0x10000)]));
+      });
+
+      it("handles UTF-8 two-byte character (¢)", () => {
```
Comment (bartblast) [inline test/javascript/erlang/unicode_util_test.mjs:739]: This test doesn't match the Elixir consistency test.

The Elixir test uses a binary input with actual UTF-8 encoded bytes:
```elixir
assert :unicode_util.cp(<<0xC2, 0xA2, 99>>) == [162 | <<99>>]
```

But this JS test uses an integer list:
```javascript
const input = Type.list([Type.integer(162), Type.bitstring("test")]);
```

These test different behaviors. The JS test should use:
```javascript
const input = Bitstring.fromBytes([0xc2, 0xa2, 99]);
const result = cp(input);

assert.deepStrictEqual(
  result,
  Type.improperList([Type.integer(162), Bitstring.fromBytes([99])]),
);
```

File: test/javascript/erlang/unicode_util_test.mjs [hunk 3]
```diff
@@ -373,5 +386,427 @@ describe("Erlang_UnicodeUtil", () => {
...
+        const input = Type.list([Type.integer(162), Type.bitstring("test")]);
+        const result = cp(input);
+
+        assert.deepStrictEqual(
+          result,
+          Type.list([Type.integer(162), Type.bitstring("test")]),
+        );
+      });
+
+      it("handles UTF-8 three-byte character (€)", () => {
```
Comment (bartblast) [inline test/javascript/erlang/unicode_util_test.mjs:749]: This test doesn't match the Elixir consistency test.

The Elixir test uses actual UTF-8 encoded bytes:
```elixir
assert :unicode_util.cp(<<0xE2, 0x82, 0xAC>>) == [8364 | ""]
```

But this JS test just uses an integer list:
```javascript
const input = Type.list([Type.integer(8364)]);
```

The JS test should use:
```javascript
const input = Bitstring.fromBytes([0xe2, 0x82, 0xac]);
const result = cp(input);

assert.deepStrictEqual(
  result,
  Type.improperList([Type.integer(8364), Type.bitstring("")]),
);
```

File: assets/js/erlang/unicode_util.mjs [hunk 4]
```diff
@@ -9,227 +9,640 @@ import Type from "../type.mjs";
...
+        list,
+        restList,
+      ]),
+    );
+  },
+  // End _cpl_cont/2
+  // Deps: [:unicode_util._cpl/2, :unicode_util._is_cp/1, :unicode_util._merge_lcr/2, :unicode_util.cp/1]
+
+  // Start _cpl_cont2/2
+  "_cpl_cont2/2": (list, restList) => {
```
Comment (bartblast) [inline assets/js/erlang/unicode_util.mjs:374]: The structure of `_cpl_cont2/2` and `_cpl_cont3/2` is very similar to `_cpl_cont/2`. These functions are 95%+ identical - they only differ in which helper functions they call (`_cpl_1_cont2/1` vs `_cpl_1_cont3/1`).

While this mirrors the Erlang implementation structure, I've created a follow-up issue to explore DRYing this up: https://github.com/bartblast/hologram/issues/638

Not blocking for this PR - the current approach is valid. If you're interested in tackling the DRY refactoring, feel free to comment on that issue.

File: test/javascript/erlang/unicode_util_test.mjs [hunk 5]
```diff
@@ -373,5 +386,427 @@ describe("Erlang_UnicodeUtil", () => {
...
+        const input = Type.list([Type.integer(97), invalidBinary]);
+        const result = cp(input);
+
+        assert.deepStrictEqual(
+          result,
+          Type.list([Type.integer(97), invalidBinary]),
+        );
+      });
+
+      it("handles very long list of integers", () => {
```
Comment (bartblast) [inline test/javascript/erlang/unicode_util_test.mjs:632]: Consider adding a brief comment explaining that this tests the O(n) optimization mentioned in the code (avoiding O(n^2) slicing behavior).

**Review by bartblast — CHANGES_REQUESTED** [review]

File: assets/js/erlang/unicode_util.mjs (hunk 4 above)
Comment (mward-sudo) [reply assets/js/erlang/unicode_util.mjs:374]: I was trying to DRY it up, but there's so much logic that I got frustrated that every time I changed something innocent looking it was breaking tests!

But that was after 4 hours of coding so many edge cases that my head was hurting 😵‍💫. Unicode is complicated.

I will take a look at the refactor once I've had some time to recover from the harrowing experience.

Comment (bartblast) [reply assets/js/erlang/unicode_util.mjs:374]: No worries! Refactoring is low priority - let's focus on shipping v0.7.0 with all the functions from phase 1 (provided they work correctly). We can revisit the refactoring later. Thanks for your work on this, I imagine this was painful! 🙏

**Comment by bartblast** [comment]
Awesome, thank you @mward-sudo! 🙏
